// WASM-backed API implementation (production / Cloudflare).
// Cheap calls (parse, validate-range, games) run on the main thread via the
// generated wasm-pkg module. The run loop is offloaded to a Web Worker which
// speaks the ServerMsg protocol identical to the daemon's WebSocket.

export type ServerMsg =
  | { type: "started"; runId?: number }
  | { type: "stdout"; line: string; runId?: number }
  | { type: "stderr"; line: string; runId?: number }
  | { type: "done"; runId?: number }
  | { type: "error"; message: string; runId?: number };

// The wasm-pkg directory is generated by `just build-wasm`. Until that runs,
// TS resolution is satisfied by ui/src/api/wasm-pkg.d.ts.
let wasmReady: Promise<typeof import("../wasm-pkg/openpql_wasm.js")> | null = null;
async function loadWasm() {
  if (!wasmReady) {
    wasmReady = (async () => {
      const mod = await import("../wasm-pkg/openpql_wasm.js");
      await mod.default();
      return mod;
    })();
  }
  return wasmReady;
}

export async function apiParse(src: string) {
  const mod = await loadWasm();
  return mod.parse_pql(src);
}

export async function apiValidateRange(game: string, text: string) {
  const mod = await loadWasm();
  return mod.validate_range(game, text);
}

export async function apiGames(): Promise<string[]> {
  const mod = await loadWasm();
  return mod.games();
}

export class RunClient {
  private worker: Worker | null = null;
  private currentRunId: number | undefined = undefined;
  private inFlight = false;
  constructor(private onMsg: (m: ServerMsg) => void) {}

  connect() {
    if (this.worker) return;
    this.worker = new Worker(
      new URL("../workers/pql.worker.ts", import.meta.url),
      { type: "module" },
    );
    this.worker.onmessage = (e: MessageEvent<ServerMsg>) => {
      const m = e.data;
      if (m && (m.type === "done" || m.type === "error")) {
        this.inFlight = false;
      }
      this.onMsg(m);
    };
    this.worker.onerror = (e) => {
      if (this.inFlight) {
        this.inFlight = false;
        this.onMsg({
          type: "error",
          message: e.message || "worker error",
          runId: this.currentRunId,
        });
      }
    };
  }

  run(src: string, runId: number) {
    this.connect();
    this.currentRunId = runId;
    this.inFlight = true;
    this.worker?.postMessage({ type: "run", src, runId });
  }

  cancel() {
    this.inFlight = false;
    this.worker?.postMessage({ type: "cancel" });
  }

  close() {
    this.worker?.terminate();
    this.worker = null;
  }
}
